[package]
name = "wm"
version = "0.1.0"
edition = "2021"

[dependencies]
slog = "2.7.0"
slog-term = "2.8.1"

[dependencies.smithay]
version = "0.3.0"
default-features = false
features = ["backend_udev", "backend_session_logind", "wayland_frontend", "xwayland"]
